/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAdm;

import data.Conexao;
import data.PerguntasData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javafx.scene.control.ComboBox;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.Pergunta;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Matheus
 */
public class FrmCadastroPerguntaAdm extends javax.swing.JInternalFrame {

    Conexao con;
    PerguntasData DAO;
    Pergunta obPerg;

    /**
     * Creates new form TelaCadastroPergunta
     */
    public FrmCadastroPerguntaAdm() {
        
        initComponents();
        DAO = new PerguntasData();
        DAO.listarPerguntas();
      
        this.setLocation(0, 0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPergunta = new javax.swing.JTextField();
        txtAlternativaA = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlternativaB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAlternativaC = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPerguntas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnRespA = new javax.swing.JRadioButton();
        btnRespB = new javax.swing.JRadioButton();
        btnRespC = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigoPergunta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmbTemas = new javax.swing.JComboBox<>();
        cmbTemaPesquisa = new javax.swing.JComboBox<>();
        btnBuscarTema = new javax.swing.JButton();

        jScrollPane2.setViewportView(jTextPane2);

        jButton3.setText("jButton3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Pergunta");
        setToolTipText("");
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pergunta:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Alternativa A:");

        txtPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerguntaActionPerformed(evt);
            }
        });

        txtAlternativaA.setAutoscrolls(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Alternativa B:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Alternativa C:");

        txtAlternativaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlternativaCActionPerformed(evt);
            }
        });

        btnNovo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/style_add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/style_edit.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/style_delete.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/disk.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tema:");

        tblPerguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPerguntas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPerguntasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPerguntas);

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Alternativa Correta:");

        btnRespA.setText("A");
        btnRespA.setEnabled(false);

        btnRespB.setText("B");
        btnRespB.setEnabled(false);

        btnRespC.setText("C");
        btnRespC.setEnabled(false);

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Código: ");

        txtCodigoPergunta.setEnabled(false);
        txtCodigoPergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPerguntaActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zoom.png"))); // NOI18N
        jLabel8.setText("Buscar por Pergunta");

        cmbTemas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tema:" }));
        cmbTemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTemasMouseClicked(evt);
            }
        });
        cmbTemas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTemasActionPerformed(evt);
            }
        });

        cmbTemaPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busque pelo Tema:" }));
        cmbTemaPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbTemaPesquisaMouseClicked(evt);
            }
        });
        cmbTemaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTemaPesquisaActionPerformed(evt);
            }
        });

        btnBuscarTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zoom.png"))); // NOI18N
        btnBuscarTema.setText("Buscar por Tema");
        btnBuscarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAlternativaC))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAlternativaB))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtAlternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(36, 36, 36)
                                .addComponent(btnRespA)
                                .addGap(18, 18, 18)
                                .addComponent(btnRespB)
                                .addGap(18, 18, 18)
                                .addComponent(btnRespC))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtCodigoPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(114, 114, 114))))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbTemaPesquisa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarTema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTemaPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarTema))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigoPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(txtPergunta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlternativaB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlternativaC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRespA)
                    .addComponent(btnRespB)
                    .addComponent(btnRespC))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerguntaActionPerformed

    private void txtAlternativaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlternativaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlternativaCActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

        limparCampos();
        txtPergunta.setEnabled(true);
        txtAlternativaA.setEnabled(true);
        txtAlternativaB.setEnabled(true);
        txtAlternativaC.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);

        btnCancelar.setEnabled(true);
        btnRespA.setEnabled(true);
        btnRespB.setEnabled(true);
        btnRespC.setEnabled(true);
        respCerto();

        btnNovo.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limparCampos();
        txtPergunta.setEnabled(true);
        txtAlternativaA.setEnabled(true);
        txtAlternativaB.setEnabled(true);
        txtAlternativaC.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnNovo.setEnabled(true);
        txtPesquisa.setEnabled(true);
        respCerto();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {

            if (validarCampos()) {
                if (preencherSalvar()) {
                    if (DAO.Incluir(obPerg)) {

                        JOptionPane.showMessageDialog(this, "Salvo com sucesso!");
                        DAO.listarPerguntas();

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Não foi possível inserir o registro");
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro:" + erro.getMessage());

        }
        DAO.listarPerguntas();
        btnCancelarActionPerformed(evt);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        txtPergunta.setEnabled(true);
        txtAlternativaA.setEnabled(true);
        txtAlternativaB.setEnabled(true);
        txtAlternativaC.setEnabled(true);
        btnRespA.setEnabled(true);
        btnRespB.setEnabled(true);
        btnRespC.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnNovo.setEnabled(true);

        DAO.listarPerguntas();

        try {
            if (validarCampos()) {
                if (preencherAlterar()) {
                    if (DAO.Editar(obPerg)) {
                        JOptionPane.showMessageDialog(this, "Editado com sucesso!");
                        DAO.listarPerguntas();
                        limparCampos();

                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Não foi possível editar a pergunta!");
                }
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro:" + erro.getMessage());
        }


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        DAO.pesquisarPergunta();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void tblPerguntasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPerguntasMouseClicked
        mostraItensCampos();
    }//GEN-LAST:event_tblPerguntasMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        try {
            if (txtPergunta.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Preencha o campo Pergunta");

            } else {
                if (DAO.Excluir(Integer.parseInt(txtCodigoPergunta.getText()))) {

                    JOptionPane.showMessageDialog(this, "Pergunta excluida com sucesso!");
                    btnCancelarActionPerformed(evt);
                } else {
                    JOptionPane.showMessageDialog(this, "Não fois possível excluir a Pergunta!");
                    btnCancelarActionPerformed(evt);
                }
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro: " + erro.getMessage());
        }

        DAO.listarPerguntas();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtCodigoPerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPerguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPerguntaActionPerformed

    private void cmbTemasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTemasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTemasActionPerformed

    private void cmbTemasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTemasMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_cmbTemasMouseClicked

    private void cmbTemaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTemaPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTemaPesquisaActionPerformed

    private void cmbTemaPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbTemaPesquisaMouseClicked
    

            // TODO add your handling code here:
    }//GEN-LAST:event_cmbTemaPesquisaMouseClicked

    private void btnBuscarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTemaActionPerformed
DAO.pesquisarPerguntaPorTema();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarTemaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscarTema;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JRadioButton btnRespA;
    private javax.swing.JRadioButton btnRespB;
    private javax.swing.JRadioButton btnRespC;
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JComboBox<String> cmbTemaPesquisa;
    private javax.swing.JComboBox<String> cmbTemas;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextPane jTextPane2;
    public static javax.swing.JTable tblPerguntas;
    private javax.swing.JTextField txtAlternativaA;
    private javax.swing.JTextField txtAlternativaB;
    private javax.swing.JTextField txtAlternativaC;
    private javax.swing.JTextField txtCodigoPergunta;
    private javax.swing.JTextField txtPergunta;
    public static javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables

    public void limparCampos() {
        txtPergunta.setText("");
        txtAlternativaA.setText("");
        txtAlternativaB.setText("");
        txtAlternativaC.setText("");
        txtCodigoPergunta.setText("");
        txtPesquisa.setText("");
        btnSalvar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnRespA.setEnabled(false);
        btnRespB.setEnabled(false);
        btnRespC.setEnabled(false);
        btnRespA.setSelected(false);
        btnRespB.setSelected(false);
        btnRespC.setSelected(false);
        cmbTemas.setSelectedItem("Escolha: ");
    }

    public boolean validarCampos() {

        if (cmbTemas.getSelectedItem().equals("Escolha: ")) {

            JOptionPane.showMessageDialog(this, "Escolha qual tema você deseja utilizar!");
            return false;
        }

        if (btnRespA.isSelected()
                && btnRespB.isSelected()
                && btnRespC.isSelected() == false) {

            JOptionPane.showMessageDialog(this, "Preencha qual das alternativas é a correta!");
            return false;
        }

        if (txtPergunta.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo Pergunta!");
            txtPergunta.requestFocus();
            return false;
        }

        if (txtAlternativaA.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo com a Alternativa A!");
            txtAlternativaA.requestFocus();
            return false;
        }

        if (txtAlternativaB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo com a Alternativa B!");
            txtAlternativaB.requestFocus();
            return false;
        }

        if (txtAlternativaC.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Preencha o campo com a Alternativa C!");
            txtAlternativaC.requestFocus();
            return false;
        }

        return true;
    }

    public void respCerto() {
        ButtonGroup tema, respCerto;

        respCerto = new ButtonGroup();
        respCerto.add(btnRespA);
        respCerto.add(btnRespB);
        respCerto.add(btnRespC);
        respCerto.clearSelection();
    }

    public boolean preencherSalvar() {
        obPerg = new Pergunta();
        obPerg.setPergunta(txtPergunta.getText());
        obPerg.setRespostaA(txtAlternativaA.getText());
        obPerg.setRespostaB(txtAlternativaB.getText());
        obPerg.setRespostaC(txtAlternativaC.getText());
        obPerg.setTema(cmbTemas.getSelectedIndex());
        if (btnRespA.isSelected()) {
            obPerg.setRespostaCerta("A");
        } else if (btnRespB.isSelected()) {
            obPerg.setRespostaCerta("B");
        } else if (btnRespC.isSelected()) {
            obPerg.setRespostaCerta("C");
        }
        
        return true;
    }

    public boolean preencherAlterar() {
        obPerg = new Pergunta();
        obPerg.setPergunta(txtPergunta.getText());
        obPerg.setRespostaA(txtAlternativaA.getText());
        obPerg.setRespostaB(txtAlternativaB.getText());
        obPerg.setRespostaC(txtAlternativaC.getText());
        obPerg.setTema(cmbTemas.getSelectedIndex());
        obPerg.setCodigoPergunta(Integer.parseInt(txtCodigoPergunta.getText()));
        if (btnRespA.isSelected()) {
            obPerg.setRespostaCerta("A");
        } else if (btnRespB.isSelected()) {
            obPerg.setRespostaCerta("B");
        } else if (btnRespC.isSelected()) {
            obPerg.setRespostaCerta("C");
        }
        
        // obPerg.setCodigoPergunta(Integer.parseInt(txtCodigo.getText()));
        return true;
    }

    public void mostraItensCampos() {
        respCerto();

        int seleciona = tblPerguntas.getSelectedRow();
        
        String respCerta;
        txtCodigoPergunta.setText(tblPerguntas.getModel().getValueAt(seleciona, 0).toString());
        txtPergunta.setText(tblPerguntas.getModel().getValueAt(seleciona, 1).toString());
        txtAlternativaA.setText(tblPerguntas.getModel().getValueAt(seleciona, 2).toString());
        txtAlternativaB.setText(tblPerguntas.getModel().getValueAt(seleciona, 3).toString());
        txtAlternativaC.setText(tblPerguntas.getModel().getValueAt(seleciona, 4).toString());
        respCerta = tblPerguntas.getModel().getValueAt(seleciona, 5).toString();
        cmbTemas.setSelectedItem(tblPerguntas.getModel().getValueAt(seleciona, 6).toString());

        if (respCerta.equals("A")) {
            btnRespA.setSelected(true);
        } else if (respCerta.equals("B")) {
            btnRespB.setSelected(true);
        } else if (respCerta.equals("C")) {
            btnRespC.setSelected(true);
        }

       

       
        btnRespA.setEnabled(true);
        btnRespB.setEnabled(true);
        btnRespC.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnExcluir.setEnabled(true);
    }

    public void comboboxTema() {
        try {
            con = new Conexao();
            String SQL = "select * from tema";
            PreparedStatement ps = con.getConexao().prepareStatement(SQL);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cmbTemas.addItem(rs.getString("nome"));
                cmbTemaPesquisa.addItem(rs.getString("nome"));
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro: " + erro.getMessage());
        }
    }
    
    public void deixarVisivel(){
        this.setVisible(true);
        cmbTemas.removeAllItems();
        cmbTemaPesquisa.removeAllItems();
        comboboxTema();
        
    }

}
