/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewAdm;

import data.HistoricoData;
import data.RankingData;
import login.FrmLogin;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mariajosineidedefrei
 */
public class FrmMenuAdm extends javax.swing.JFrame {
    
    FrmCadastroUsuariosAdm frmUser = new FrmCadastroUsuariosAdm();
    FrmCadastroPerguntaAdm frmPergunta = new FrmCadastroPerguntaAdm();
    FrmCadastroTemaAdm frmTema = new FrmCadastroTemaAdm();
    FrmLogin TelaLogin;
    FrmJogadas TelaJogadas = new FrmJogadas();
    HistoricoData DAO = new HistoricoData(); 
    /**
     * Creates new form TelaAdm
     */
    public FrmMenuAdm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuario = new javax.swing.JMenu();
        menuControleUsuario = new javax.swing.JMenuItem();
        menuPergunta = new javax.swing.JMenu();
        menuControlePergunta = new javax.swing.JMenuItem();
        menuControleTema = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuJogadas = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();
        menuVoltarComeco = new javax.swing.JMenuItem();
        menuSairTotal = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administração");
        setIconImage(new ImageIcon(getClass().getResource("/icones/icon.png")).getImage());

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(826, 661));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 557, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 424, Short.MAX_VALUE)
        );

        menuUsuario.setForeground(java.awt.Color.blue);
        menuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/user.png"))); // NOI18N
        menuUsuario.setText("Usuários");

        menuControleUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/user_edit.png"))); // NOI18N
        menuControleUsuario.setText("Controle de Usuários");
        menuControleUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuControleUsuario);

        jMenuBar1.add(menuUsuario);

        menuPergunta.setForeground(java.awt.Color.blue);
        menuPergunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vcard.png"))); // NOI18N
        menuPergunta.setText("Perguntas & Respostas");

        menuControlePergunta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menuControlePergunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vcard_add.png"))); // NOI18N
        menuControlePergunta.setText("Controle de Perguntas e respostas");
        menuControlePergunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControlePerguntaActionPerformed(evt);
            }
        });
        menuPergunta.add(menuControlePergunta);

        menuControleTema.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        menuControleTema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/vcard_add.png"))); // NOI18N
        menuControleTema.setText("Controle de Temas");
        menuControleTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleTemaActionPerformed(evt);
            }
        });
        menuPergunta.add(menuControleTema);

        jMenuBar1.add(menuPergunta);

        jMenu1.setForeground(new java.awt.Color(0, 0, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application.png"))); // NOI18N
        jMenu1.setText("Jogadas");

        menuJogadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/application_form_magnify.png"))); // NOI18N
        menuJogadas.setText("Todas as jogadas");
        menuJogadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJogadasActionPerformed(evt);
            }
        });
        jMenu1.add(menuJogadas);

        jMenuBar1.add(jMenu1);

        menuSair.setForeground(java.awt.Color.blue);
        menuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/stop.png"))); // NOI18N
        menuSair.setText("Sair");

        menuVoltarComeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/arrow_rotate_anticlockwise.png"))); // NOI18N
        menuVoltarComeco.setText("Voltar Para a Tela de Login");
        menuVoltarComeco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuVoltarComecoActionPerformed(evt);
            }
        });
        menuSair.add(menuVoltarComeco);

        menuSairTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancel.png"))); // NOI18N
        menuSairTotal.setText("Fechar Programa");
        menuSairTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairTotalActionPerformed(evt);
            }
        });
        menuSair.add(menuSairTotal);

        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void menuControleUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleUsuarioActionPerformed
        fecharTodos();
        frmUser.setVisible(true);
        jDesktopPane1.add(frmUser);
        this.setSize(692, 623);

    }//GEN-LAST:event_menuControleUsuarioActionPerformed

    private void menuControlePerguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControlePerguntaActionPerformed

        fecharTodos();
        frmPergunta.deixarVisivel();
        jDesktopPane1.add(frmPergunta);
        this.setSize(838, 762);

        // TODO add your handling code here:
    }//GEN-LAST:event_menuControlePerguntaActionPerformed

    private void menuControleTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleTemaActionPerformed
       fecharTodos();
        frmTema.setVisible(true);
        jDesktopPane1.add(frmTema);
        this.setSize(687,621);
               
    }//GEN-LAST:event_menuControleTemaActionPerformed

    private void menuSairTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairTotalActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairTotalActionPerformed

    private void menuVoltarComecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVoltarComecoActionPerformed
        TelaLogin = new FrmLogin();
        TelaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuVoltarComecoActionPerformed

    private void menuJogadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJogadasActionPerformed
        
        fecharTodos();
       
        TelaJogadas.setVisible(true);
        
        jDesktopPane1.add(TelaJogadas);
        DAO.listarPerguntas();
        this.setSize(690, 608);

        // TODO add your handling code here:
    }//GEN-LAST:event_menuJogadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuControlePergunta;
    private javax.swing.JMenuItem menuControleTema;
    private javax.swing.JMenuItem menuControleUsuario;
    private javax.swing.JMenuItem menuJogadas;
    private javax.swing.JMenu menuPergunta;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem menuSairTotal;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JMenuItem menuVoltarComeco;
    // End of variables declaration//GEN-END:variables

    public void fecharTodos() {
        frmUser.setVisible(false);
        frmPergunta.setVisible(false);
        frmTema.setVisible(false);
        TelaJogadas.setVisible(false);
        frmUser.dispose();
        frmPergunta.dispose();
        frmTema.dispose();
        TelaJogadas.dispose();
        jDesktopPane1.remove(frmUser);
        jDesktopPane1.remove(frmPergunta);
        jDesktopPane1.remove(TelaJogadas);
        jDesktopPane1.remove(frmTema);
       // if (frmUser.getParent() != jDesktopPane1) {  
           //     jDesktopPane1.add(F);  
  

    }
    
}
